plugins { id 'com.android.application' }

android {
    namespace 'com.bellamiecreative.iphonestylekeyboard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bellamiecreative.iphonestylekeyboard'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
